package tools

import (
	"context"
	"fmt"

	"github.com/edouard-claude/redmine-mcp/internal/redmine"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

func registerCreateUser(s *server.MCPServer, client *redmine.Client) {
	tool := mcp.NewTool("create_user",
		mcp.WithDescription("Create a new Redmine user account (requires an admin API key). Without a password, Redmine generates one. The account is not member of any project yet — follow up with add_project_member."),
		mcp.WithString("login",
			mcp.Description("Login/username"),
			mcp.Required(),
		),
		mcp.WithString("firstname",
			mcp.Description("First name"),
			mcp.Required(),
		),
		mcp.WithString("lastname",
			mcp.Description("Last name"),
			mcp.Required(),
		),
		mcp.WithString("mail",
			mcp.Description("Email address"),
			mcp.Required(),
		),
		mcp.WithString("password",
			mcp.Description("Initial password (empty = let Redmine generate one)"),
		),
		mcp.WithBoolean("send_information",
			mcp.Description("Email the account information (including the password) to the user (default false)"),
		),
		mcp.WithBoolean("must_change_password",
			mcp.Description("Force a password change at first login (default false)"),
		),
		mcp.WithReadOnlyHintAnnotation(false),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithIdempotentHintAnnotation(false),
		mcp.WithOpenWorldHintAnnotation(true),
	)

	s.AddTool(tool, func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := redmine.UserCreateParams{
			Login:            req.GetString("login", ""),
			Firstname:        req.GetString("firstname", ""),
			Lastname:         req.GetString("lastname", ""),
			Mail:             req.GetString("mail", ""),
			Password:         req.GetString("password", ""),
			MustChangePasswd: req.GetBool("must_change_password", false),
		}
		if params.Login == "" || params.Firstname == "" || params.Lastname == "" || params.Mail == "" {
			return mcp.NewToolResultError("login, firstname, lastname and mail are required"), nil
		}
		if params.Password == "" {
			params.GeneratePassword = true
		}
		sendInfo := req.GetBool("send_information", false)

		passwordMode := "generated by Redmine"
		if params.Password != "" {
			passwordMode = "provided by the caller"
		}
		notify := "no"
		if sendInfo {
			notify = "yes, credentials emailed to the user"
		}
		if abort := confirmWrite(ctx, s,
			fmt.Sprintf("Create user account %q on %s", params.Login, client.BaseURL()),
			[]string{
				summarize("Name", params.Firstname+" "+params.Lastname),
				summarize("Email", params.Mail),
				summarize("Password", passwordMode),
				summarize("Send account info by email", notify),
			}); abort != nil {
			return abort, nil
		}

		user, err := client.CreateUser(params, sendInfo)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("create failed: %v", err)), nil
		}

		return mcp.NewToolResultText(fmt.Sprintf("User #%d created: %s %s (%s, %s)\n%s/users/%d\nAdd them to a project with add_project_member.",
			user.ID, user.Firstname, user.Lastname, user.Login, user.Mail, client.BaseURL(), user.ID)), nil
	})
}
